Removing Openssl Connector changes and keeping thr original content

diff --git a/.github/workflows/openssl_connector_unittest.yml b/.github/workflows/openssl_connector_unittest.yml
--- a/.github/workflows/openssl_connector_unittest.yml
+++ b/.github/workflows/openssl_connector_unittest.yml
@@ -1,8 +1,6 @@
 name: OpenSSL Connector Unit Tests
+
 on:
-  workflow_dispatch: {}
-  push:
-    branches: ["DTM-8744-github-action-for-coverage-summary"] 
   pull_request:
     paths:
       - "scripts/openssl/**"
@@ -15,7 +13,7 @@ permissions:
 
 jobs:
   OpenSSLConnectorUnitTest:
-    runs-on: [ubuntu-22.04]
+    runs-on: [ubuntu-latest]
     strategy:
       matrix:
         openssl_version: ["3.0.7", "3.0.12"]
@@ -27,8 +25,6 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y build-essential wget tar make gcc patch
-          sudo apt-get install -y lcov
-          lcov --version
 
       - name: Patch OpenSSL ${{ matrix.openssl_version }}
         run: |
@@ -37,26 +33,37 @@ jobs:
           tar -xzf openssl-${{ matrix.openssl_version }}.tar.gz -C thirdparty/
           cd scripts/openssl
           ./apply-patch.sh openssl-${{ matrix.openssl_version }}
-          
-      - name: Clean build and coverage artifacts
+
+      - name: Build OpenSSL ${{ matrix.openssl_version }} with DigiCert provider
         run: |
-          echo "Cleaning previous build and coverage files..."
-          find . -name "*.gcda" -delete
-          find . -name "*.gcno" -delete
+          if [ "${{ matrix.openssl_version }}" = "3.0.7" ]; then
+            ./scripts/nanossl/openssl_connector_test/build_digiprov_test.sh --build-for-osi --openssl_3_0_7 --ossl-digi-test
+          else
+            ./scripts/nanossl/openssl_connector_test/build_digiprov_test.sh --build-for-osi --openssl_3_0_12 --ossl-digi-test
+          fi
+
+      - name: Run digiprov_test
+        run: |
+          LD_LIBRARY_PATH=$PWD/lib ./lib/digiprov_test || (echo "digiprov_test failed" && exit 1)
+
+      - name: Run OpenSSL CMS tests
+        run: |
+          cd thirdparty/openssl-${{ matrix.openssl_version }}
+          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib make TESTS=test_cms test
 
       - name: Build OpenSSL Connector for testing
-        env:
-          CM_ENV_CODE_COVERAGE: 1
         run: |
           if [ "${{ matrix.openssl_version }}" = "3.0.7" ]; then
             ./scripts/nanossl/openssl_connector/build_openssl_connector_tap_local.sh --build-for-osi --openssl_3_0_7
           else
             ./scripts/nanossl/openssl_connector/build_openssl_connector_tap_local.sh --build-for-osi --openssl_3_0_12
           fi
-          
-      - name: Baseline Coverage
+
+      - name: Run OpenSSL Crypto Tests
         run: |
-          lcov --no-external --capture --initial --directory . --output-file /tmp/ossl_base2_${{ matrix.openssl_version }}.info
+          cd thirdparty/openssl-${{ matrix.openssl_version }}
+          LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib make TESTS=test_evp test
+
       - name: Run OpenSSL SSL Tests
         run: |
           cd thirdparty/openssl-${{ matrix.openssl_version }}/sample
@@ -64,14 +71,3 @@ jobs:
           LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib ./openssl_server --ssl_certpath $GITHUB_WORKSPACE/keystore --ssl_server_cert certs/rsa_cert.pem --ssl_server_keyblob keys/rsa_key.pem &
           sleep 2
           LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib ./openssl_client_local --ssl_certpath $GITHUB_WORKSPACE/keystore --ssl_ca_cert ca/rsa_ca.pem --ssl_servername rsa-test
-
-      - name: Capture Coverage
-        run: |
-          lcov --no-external --capture --directory . --output-file /tmp/ossl_test2_${{ matrix.openssl_version }}.info
-
-      - name: Print Coverage Summary for OpenSSL Connector
-        run: |
-          echo "Coverage Summary:"
-          lcov --add-tracefile /tmp/ossl_base2_${{ matrix.openssl_version }}.info --add-tracefile /tmp/ossl_test2_${{ matrix.openssl_version }}.info --output-file /tmp/ossl_total2_${{ matrix.openssl_version }}.info
-          lcov --list /tmp/ossl_total2_${{ matrix.openssl_version }}.info
-
